name: build-and-run
run-name: building/running SimpleSSD-SA
on: [push]
jobs:
  build-and-run:
    runs-on: ubuntu-20.04
    steps:
      - name: init repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SSS_PAT_EXP250130 }}
          submodules: recursive
      - name: prepare env
        run: sudo apt-get -y update && sudo apt-get -y install build-essential cmake e2fsprogs libext2fs-dev libzstd-dev libpcre++-dev
      - name: build
        run: cmake -B . && cmake --build . -j`nproc`
      - name: create and init ext4 disk
        run: make -f simplessd/isc/scripts/Makefile ext4-init EXT4_INIT_SCRIPT_FILES=md5-many-4k.sh
      - name: link ext4 disk as ssd disk
        run: ln -s /tmp/nvme.img .
      - name: run
        run: make -f scripts/Makefile test-slet KEYS="path" VALUES="/md5/x100/" SLET_ID=2
      - name: show logs
        run: bash -c 'cat ./logs-sa/$(date +%y%m)/test-slet/sssa-test-slet/*.debug.log'
